### ISSUE TITLE
Typechecker allows boolean + boolean at the moment in exprBinaryOp 

### ISSUE THREAD

**Issue by christopher-jensen** [humleflue/P4#43]

**Comment by laurits-mumberg** [comment]
Problemet gælder så vidt jeg kan se for alle de her operators. Bools kan bruges på alle.
https://github.com/humleflue/P4/blob/d90eea3e50ee677db42d177700d3bf16e103617c/ANTLR/src/Compiler/ContextualAnalysis/TypeCheckerVisitor.java#L80-L82
